# Generated by Django 5.1.7 on 2025-03-21 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe_servings_alter_recipe_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Grams'), ('ml', 'Milliliters'), ('cup', 'Cups'), ('tbsp', 'Tablespoons'), ('tsp', 'Teaspoons'), ('unit', 'Whole Unit'), ('none', 'None')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_covers/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='last_cooked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='times_cooked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recipe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag')),
            ],
            options={
                'unique_together': {('recipe', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(through='api.RecipeTag', to='api.tag'),
        ),
    ]
