# Generated by Django 5.1.7 on 2025-03-24 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recipe_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
    ]
