/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HeaderMenuView: typeof import('./src/components/HeaderMenuView.vue')['default']
    IngredientList: typeof import('./src/components/IngredientList.vue')['default']
    RecipeStepBasics: typeof import('./src/components/RecipeSteps/RecipeStepBasics.vue')['default']
    RecipeStepIngredients: typeof import('./src/components/RecipeSteps/RecipeStepIngredients.vue')['default']
    RecipeStepInstructions: typeof import('./src/components/RecipeSteps/RecipeStepInstructions.vue')['default']
    RecipeStepsIngredients: typeof import('./src/components/RecipeSteps/RecipeStepsIngredients.vue')['default']
    RecipeStepTags: typeof import('./src/components/RecipeSteps/RecipeStepTags.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  }
}
