services:

# Frontend Service
  frontend:
    build: ./frontend
    container_name: bitebook_frontend
    ports:
      - "5173:5173"  # Vue dev server
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Avoid volume issues
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev"

# Backend Service
  backend:
    build: ./backend
    container_name: bitebook_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

# Database Service
  db:
    image: postgres:15
    container_name: bitebook_db
    restart: no
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
